# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: home
    weight: 10
  - name: About
    weight: 20
  - parent: About
    name: Introduce
    url: intro
    weight: 30
  - parent: About
    name: Hobby
    url: certification
    weight: 40  
  - parent: About
    name: Blog
    url: blog
    weight: 50  
  - name: Experience
    weight: 50  
  - parent: Experience
    name: Project
    url: pro
    weight: 60
  - name: Contact
    url: contact
    weight: 70
  - name : ex
    url: ex
    weight: 80
